/**
 * Read-only view of the EXISTING service worker, and a manual update check.
 *
 * The app registers its worker through the script generated by
 * vite-plugin-pwa (`registerType: 'autoUpdate'`, see vite.config.ts); nothing
 * here registers, unregisters or replaces it. `update()` only asks the browser
 * to look for a new worker file, exactly what it already does on its own.
 *
 * What autoUpdate means in practice (verified in the generated `sw.js`, which
 * calls `skipWaiting()` and `clientsClaim()`): a new worker installs and takes
 * control as soon as it is downloaded, but the page that is already open keeps
 * running the old JavaScript until it is reloaded or the app is reopened.
 */
export interface ServiceWorkerInfo {
  supported: boolean
  /** A worker is registered for this page. */
  registered: boolean
  /** Controlling the current page (false on the very first visit). */
  controlled: boolean
  /** Lifecycle state of the active worker. */
  state: ServiceWorkerState | null
  /** A newer worker is installing or waiting right now. */
  updatePending: boolean
}

export type UpdateCheckResult =
  'unsupported' | 'not-registered' | 'up-to-date' | 'update-found' | 'error'

function container(): ServiceWorkerContainer | null {
  if (typeof navigator === 'undefined' || !('serviceWorker' in navigator)) return null
  return navigator.serviceWorker
}

export async function readServiceWorkerInfo(): Promise<ServiceWorkerInfo> {
  const sw = container()
  if (!sw) {
    return {
      supported: false,
      registered: false,
      controlled: false,
      state: null,
      updatePending: false,
    }
  }
  try {
    const registration = await sw.getRegistration()
    if (!registration) {
      return {
        supported: true,
        registered: false,
        controlled: false,
        state: null,
        updatePending: false,
      }
    }
    return {
      supported: true,
      registered: true,
      controlled: sw.controller !== null,
      state: registration.active?.state ?? null,
      updatePending: Boolean(registration.installing ?? registration.waiting),
    }
  } catch {
    return {
      supported: true,
      registered: false,
      controlled: false,
      state: null,
      updatePending: false,
    }
  }
}

/** How long to wait for a worker to start installing after `update()`. */
export const UPDATE_SETTLE_MS = 1500

export async function checkForServiceWorkerUpdate(
  settleMs: number = UPDATE_SETTLE_MS,
): Promise<UpdateCheckResult> {
  const sw = container()
  if (!sw) return 'unsupported'
  try {
    const registration = await sw.getRegistration()
    if (!registration) return 'not-registered'

    let found = false
    const onFound = () => {
      found = true
    }
    registration.addEventListener('updatefound', onFound)
    try {
      await registration.update()
      if (!found && !registration.installing && !registration.waiting) {
        // The new worker, if any, is announced just after update() resolves.
        await new Promise((resolve) => setTimeout(resolve, settleMs))
      }
      return found || registration.installing || registration.waiting
        ? 'update-found'
        : 'up-to-date'
    } finally {
      registration.removeEventListener('updatefound', onFound)
    }
  } catch {
    // Offline, blocked, or the server refused: say so, never claim « à jour ».
    return 'error'
  }
}
